# Generated by Django 5.0.3 on 2024-03-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventario',
            new_name='Carro',
        ),
    ]
